// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	ID   string   `json:"id"`
	URL  string   `json:"url"`
	Tags []string `json:"tags"`
}

type ImageTagsInput struct {
	ImageID string   `json:"imageId"`
	Tags    []string `json:"tags"`
}
